import type {World} from '../ecs/world';
import type {InputState} from '../input';
import {ABILITIES, type GameState, RAINBOW_COLORS, STAGE_COUNT, VIEW_HEIGHT, VIEW_WIDTH, WORLD_HEIGHT, WORLD_WIDTH} from '../state';
import unicornUrl from '../assets/unicorn-atlas.webp';
import enemyUrl from '../assets/enemy-atlas.webp';

interface Rect {x:number;y:number;width:number;height:number}

export class RenderSystem {
  cameraX=WORLD_WIDTH/2; cameraY=WORLD_HEIGHT/2; viewWidth=VIEW_WIDTH; viewHeight=VIEW_HEIGHT; visiblePrisms=0;
  private stride=0;private lastPlayerX=NaN;private lastPlayerY=NaN;private readonly unicorn=new Image();private readonly enemy=new Image();
  constructor(private readonly context:CanvasRenderingContext2D,private readonly input:InputState){this.unicorn.src=unicornUrl;this.enemy.src=enemyUrl;this.context.imageSmoothingEnabled=false}

  draw(world:World,state:GameState,time:number):void{
    const {canvas}=this.context,scale=Math.max(canvas.width/VIEW_WIDTH,canvas.height/VIEW_HEIGHT);
    this.viewWidth=canvas.width/scale;this.viewHeight=canvas.height/scale;
    const player=world.players.values().next().value,pp=player===undefined?undefined:world.positions.get(player);
    const clamp=(v:number,s:number,l:number)=>Math.max(s/2,Math.min(l-s/2,v));
    this.cameraX=clamp(pp?.x??WORLD_WIDTH/2,this.viewWidth,WORLD_WIDTH);this.cameraY=clamp(pp?.y??WORLD_HEIGHT/2,this.viewHeight,WORLD_HEIGHT);this.visiblePrisms=0;
    this.context.fillStyle='#090611';this.context.fillRect(0,0,canvas.width,canvas.height);this.context.save();
    this.context.translate(canvas.width/2,canvas.height/2);this.context.scale(scale,scale);this.context.translate(-this.cameraX,-this.cameraY);this.drawArena();
    for(const prism of world.prisms){if(world.consumed.has(prism))continue;const p=world.positions.get(prism),c=world.prismColors.get(prism);if(p&&c){if(Math.abs(p.x-this.cameraX)<this.viewWidth/2+24&&Math.abs(p.y-this.cameraY)<this.viewHeight/2+24)this.visiblePrisms++;this.drawPrism(p.x,p.y,time+prism*300,c.index)}}
    if(pp&&state.abilities&1<<7)this.drawAura(pp.x,pp.y,time);
    for(const [entity,shot]of world.projectiles){if(world.consumed.has(entity))continue;const p=world.positions.get(entity);if(p)this.drawShot(p.x,p.y,shot.friendly,time+entity*90,!!pp&&!shot.friendly&&!!(state.abilities&1<<7)&&Math.hypot(p.x-pp.x,p.y-pp.y)<220)}
    for(const [entity,enemy]of world.enemies){if(world.consumed.has(entity))continue;const p=world.positions.get(entity),v=world.velocities.get(entity),d=p&&pp?Math.hypot(p.x-pp.x,p.y-pp.y):999;if(p)this.drawEnemy(p.x,p.y,enemy.type,enemy.health,!!pp&&!!(state.abilities&1<<7)&&d<220,pp?.x??p.x,state.phase==='play'&&Math.hypot(v?.x??0,v?.y??0)>1?time+entity*97:0,enemy.type===1&&d<260&&(world.cooldowns.get(entity)?.value??1)<.25)}
    if(pp&&player!==undefined){const f=world.facings.get(player)??{x:1,y:0},v=world.velocities.get(player),moving=state.phase==='play'&&Math.hypot(v?.x??0,v?.y??0)>1,d=Math.hypot(pp.x-this.lastPlayerX,pp.y-this.lastPlayerY);if(moving&&Number.isFinite(d)&&d<40)this.stride+=d*.08;else if(!moving)this.stride=0;this.lastPlayerX=pp.x;this.lastPlayerY=pp.y;if(state.meleeFlash>0)this.drawCharge(pp.x,pp.y,f.x,f.y,state.meleeFlash);this.drawUnicorn(pp.x,pp.y,f.x,f.y,state.invulnerable>0,1,moving);if(state.shieldAvailable)this.drawShield(pp.x,pp.y,time)}
    this.context.restore();this.drawHud(world,state);if(state.phase==='play'){this.drawStick();this.drawAttack(state)}else this.drawOverlay(state);
    if(DEBUG){this.context.textAlign='left';this.context.font='12px monospace';this.context.fillStyle='#7cf';this.context.fillText(`DEBUG: x=${pp?.x.toFixed(1)} y=${pp?.y.toFixed(1)} enemies=${world.enemies.size} shots=${world.projectiles.size}`,16,canvas.height-14)}
  }

  choiceAt(x:number,y:number):number{return this.choiceRects().findIndex(c=>x>=c.x&&x<=c.x+c.width&&y>=c.y&&y<=c.y+c.height)}
  attackAt(x:number,y:number,state:GameState):boolean{if(!(state.abilities&1<<2))return false;const b=this.attackRect();return Math.hypot(x-(b.x+b.width/2),y-(b.y+b.height/2))<b.width/2}

  private drawArena():void{this.context.fillStyle='#1a1030';this.context.fillRect(0,0,WORLD_WIDTH,WORLD_HEIGHT);this.context.strokeStyle='#35245a';this.context.lineWidth=2;for(let x=0;x<=WORLD_WIDTH;x+=60){this.context.beginPath();this.context.moveTo(x,0);this.context.lineTo(x,WORLD_HEIGHT);this.context.stroke()}for(let y=0;y<=WORLD_HEIGHT;y+=60){this.context.beginPath();this.context.moveTo(0,y);this.context.lineTo(WORLD_WIDTH,y);this.context.stroke()}}
  private drawPrism(x:number,y:number,time:number,color:number):void{this.context.save();this.context.translate(x,y);this.context.rotate(time/900);this.context.fillStyle=RAINBOW_COLORS[color]??'#fff';this.context.beginPath();this.context.moveTo(0,-22);this.context.lineTo(14,0);this.context.lineTo(0,22);this.context.lineTo(-14,0);this.context.closePath();this.context.fill();this.context.fillStyle='#fff7';this.context.beginPath();this.context.moveTo(0,-22);this.context.lineTo(0,0);this.context.lineTo(-14,0);this.context.fill();this.context.restore()}
  private drawEnemy(x:number,y:number,type:number,health:number,slowed:boolean,targetX:number,time:number,charging:boolean):void{const c=this.context;c.save();c.translate(Math.round(x),Math.round(y));c.imageSmoothingEnabled=false;if(type===0){const s=time?Math.sin(time/150):0,b=Math.round(Math.abs(s)*3),w=Math.round(s*2),k=Math.round(s*3);c.fillStyle='#05030a88';c.fillRect(-21,27,42,4);c.translate(w,-b);c.scale(targetX<x?-1:1,1);c.rotate(s*.035);if(this.enemy.complete){c.drawImage(this.enemy,0,0,64,48,-32,-32,64,48);c.drawImage(this.enemy,0,46,32,18,-32+k,14-Math.max(0,k),32,18);c.drawImage(this.enemy,32,46,32,18,-k,14-Math.max(0,-k),32,18)}}else if(type===1){const s=time?Math.sin(time/250):0,w=time?Math.round(Math.sin(time/180)*2):0,k=time?Math.round(Math.sin(time/140)*3):0;c.fillStyle='#05030a77';c.fillRect(-20,27,40,4);c.translate(w,Math.round(s*3));c.scale(targetX<x?-1:1,1);c.rotate(w*.012);if(this.enemy.complete){c.drawImage(this.enemy,64,0,64,46,-32,-32,64,46);c.drawImage(this.enemy,64,40,64,24,-32+k,8,64,24)}c.fillStyle='#6ef';for(let i=0;i<2;i++)c.fillRect(Math.round(Math.cos(time/260+i*3.14)*27)-2,Math.round(Math.sin(time/260+i*3.14)*16)-2,4,4);if(charging){c.fillStyle='#fff';c.fillRect(-2,-2,5,5)}}else{const s=time?Math.sin(time/240):0,b=Math.round(Math.abs(s)*2),w=Math.round(s*2),q=Math.abs(s)*.018;c.fillStyle='#05030a99';c.fillRect(-40,39,80,6);c.translate(w,-b);c.scale(targetX<x?-1:1,1);c.rotate(s*.018);c.scale(1+q,1-q);if(this.enemy.complete){c.drawImage(this.enemy,128,0,96,68,-48,-48,96,68);for(let i=0;i<4;i++){const k=time?Math.max(0,Math.round(Math.sin(time/190+(i&1)*3.14)*3)):0;c.drawImage(this.enemy,128+i*24,62,24,34,-48+i*24,14+k,24,34)}}c.fillStyle='#ff9d00';for(let i=0;i<Math.ceil(health);i++)c.fillRect(-29+i*10,-55,7,4)}if(slowed){c.strokeStyle='#75fff0';c.lineWidth=5;c.beginPath();c.arc(0,0,type===2?56:34,0,7);c.stroke()}c.restore()}
  private drawShot(x:number,y:number,friendly:boolean,time:number,slowed:boolean):void{this.context.fillStyle=friendly?(RAINBOW_COLORS[Math.floor(time/120)%7]??'#fff'):'#ff3355';this.context.beginPath();this.context.arc(x,y,friendly?13:10,0,7);this.context.fill();if(slowed){this.context.strokeStyle='#75fff0';this.context.lineWidth=3;this.context.stroke()}}
  private drawCharge(x:number,y:number,fx:number,fy:number,life:number):void{for(let i=3;i>0;i--)this.drawUnicorn(x+fx*i*28,y+fy*i*28,fx,fy,false,life/.18*(.14+i*.08),false)}
  private drawAura(x:number,y:number,time:number):void{this.context.fillStyle='#64ffe818';this.context.strokeStyle='#75fff0aa';this.context.lineWidth=5;this.context.beginPath();this.context.arc(x,y,220+Math.sin(time/180)*5,0,7);this.context.fill();this.context.stroke()}
  private drawShield(x:number,y:number,time:number):void{this.context.save();this.context.translate(x,y);this.context.rotate(time/700);this.context.fillStyle='#ffe66a18';this.context.strokeStyle='#fff39a';this.context.lineWidth=6;this.context.setLineDash([18,8]);this.context.beginPath();this.context.arc(0,0,42,0,7);this.context.fill();this.context.stroke();this.context.restore()}
  private drawUnicorn(x:number,y:number,fx:number,fy:number,blink:boolean,alpha=1,moving=false):void{const sector=(Math.round(Math.atan2(fy,fx)/(Math.PI/4))+8)%8,map=[1,3,2,3,1,4,0,4],cell=map[sector]??1,flip=sector===3||sector===4||sector===7?-1:1,wave=moving?Math.sin(this.stride):0,step=Math.round(wave),bob=moving?Math.abs(Math.round(Math.sin(this.stride))):0;this.context.save();this.context.translate(Math.round(x),Math.round(y-bob));this.context.scale(flip,1);this.context.rotate(wave*.025);this.context.globalAlpha=alpha*(blink&&Math.floor(performance.now()/80)%2?.35:1);if(this.unicorn.complete){const sx=cell*64;if(sector===6||sector%2)this.context.drawImage(this.unicorn,sx,0,64,64,-32,-32,64,64);else{this.context.drawImage(this.unicorn,sx,0,64,48,-32,-32,64,48);this.context.drawImage(this.unicorn,sx,44,32,20,-32+step,12-Math.max(0,step),32,20);this.context.drawImage(this.unicorn,sx+32,44,32,20,-step,12-Math.max(0,-step),32,20)}}this.context.restore()}

  private drawHud(world:World,state:GameState):void{const{canvas}=this.context;this.context.textAlign='left';this.context.font='bold 18px monospace';this.context.fillStyle='#fff';this.context.fillText(`RAINBOW ${state.collected}/${state.total}`,16,28);this.context.textAlign='right';this.context.fillText(`STAGE ${state.stage+1}/${STAGE_COUNT}`,canvas.width-16,28);for(let color=0;color<7;color++){const x=25+color*24;this.context.save();this.context.translate(x,51);this.context.rotate(Math.PI/4);this.context.fillStyle=state.rainbowMask&1<<color?(RAINBOW_COLORS[color]??'#fff'):'#21182e';this.context.fillRect(-6,-6,12,12);this.context.strokeStyle=RAINBOW_COLORS[color]??'#fff';this.context.strokeRect(-6,-6,12,12);this.context.restore()}if(state.abilities&3)this.drawMap(world,state);if(state.shieldAvailable){this.context.textAlign='left';this.context.fillStyle='#7ef';this.context.font='bold 14px monospace';this.context.fillText('SHIELD',16,76)}}
  private drawMap(world:World,state:GameState):void{const{canvas}=this.context,w=Math.min(140,canvas.width*.32),h=w*.7,x=canvas.width-w-12,y=40;this.context.fillStyle=state.abilities&1?'#1a1030dd':'#000d';this.context.fillRect(x,y,w,h);this.context.strokeStyle='#fff5';this.context.strokeRect(x,y,w,h);const dot=(px:number,py:number,color:string,size=3)=>{this.context.fillStyle=color;this.context.fillRect(x+px/WORLD_WIDTH*w-size/2,y+py/WORLD_HEIGHT*h-size/2,size,size)};if(state.abilities&1)for(const prism of world.prisms){const p=world.positions.get(prism),c=world.prismColors.get(prism);if(p&&c)dot(p.x,p.y,RAINBOW_COLORS[c.index]??'#fff',4)}if(state.abilities&2)for(const entity of world.enemies.keys()){const p=world.positions.get(entity);if(p)dot(p.x,p.y,'#ff4b6e',4)}const player=world.players.values().next().value,p=player===undefined?undefined:world.positions.get(player);if(p)dot(p.x,p.y,'#fff',6)}
  private drawStick():void{if(this.input.touchId<0)return;const{x:cx,y:cy}=this.context.canvas.getBoundingClientRect(),x=this.input.stickX-cx,y=this.input.stickY-cy;this.context.fillStyle='#ffffff22';this.context.beginPath();this.context.arc(x,y,44,0,7);this.context.fill();this.context.fillStyle='#ffffff88';this.context.beginPath();this.context.arc(x+this.input.moveX*28,y+this.input.moveY*28,18,0,7);this.context.fill()}
  private attackRect():Rect{const{canvas}=this.context,size=Math.min(82,canvas.width*.2);return{x:canvas.width-size-22,y:canvas.height-size-24,width:size,height:size}}
  private drawAttack(state:GameState):void{if(!(state.abilities&1<<2))return;const b=this.attackRect();this.context.fillStyle='#ff66cc55';this.context.beginPath();this.context.arc(b.x+b.width/2,b.y+b.height/2,b.width/2,0,7);this.context.fill();this.context.textAlign='center';this.context.fillStyle='#fff';this.context.font='bold 13px monospace';this.context.fillText('HORN',b.x+b.width/2,b.y+b.height/2+5)}
  private drawOverlay(state:GameState):void{const{canvas}=this.context;this.context.fillStyle='#090611e8';this.context.fillRect(0,0,canvas.width,canvas.height);this.context.textAlign='center';this.context.fillStyle='#fff';this.context.font='bold 24px monospace';if(state.phase==='upgrade'){const cards=this.choiceRects(),top=Math.min(...cards.map(c=>c.y)),bottom=Math.max(...cards.map(c=>c.y+c.height));this.context.font=`bold ${canvas.width<500?18:24}px monospace`;this.context.fillText(`STAGE ${state.stage+1} CLEAR - PICK 1 SKILL`,canvas.width/2,Math.max(28,top-18));cards.forEach((card,index)=>{const active=!!(state.abilities&1<<index),selected=index===state.selectedAbility;this.context.fillStyle=active?'#152d2b':selected?'#7f4cff':'#23143c';this.context.fillRect(card.x,card.y,card.width,card.height);this.context.strokeStyle=selected&&!active?'#fff':'#6f5a91';this.context.lineWidth=2;this.context.strokeRect(card.x,card.y,card.width,card.height);this.context.fillStyle='#fff';this.context.font=`bold ${card.width<120?10:13}px monospace`;this.context.fillText(active?'ON':ABILITIES[index]?.[0]??'',card.x+card.width/2,card.y+card.height/2+4)});this.context.font=`${canvas.width<500?10:13}px monospace`;this.context.fillStyle='#e3d8f5';const ability=ABILITIES[state.selectedAbility];this.context.fillText(ability?.[1]??'',canvas.width/2,Math.min(canvas.height-34,bottom+22));this.context.fillStyle='#a996ca';this.context.fillText('ARROWS + SPACE  |  TAP TWICE',canvas.width/2,Math.min(canvas.height-14,bottom+42))}else if(state.phase==='failed'){this.context.fillText('THE RAINBOW BROKE',canvas.width/2,canvas.height/2-12);this.context.font='16px monospace';this.context.fillText('PRESS R TO RETRY THIS STAGE',canvas.width/2,canvas.height/2+26)}else{this.context.fillText('ALL 10 RAINBOWS COMPLETE',canvas.width/2,canvas.height/2-12);this.context.font='16px monospace';this.context.fillText('PRESS R TO RESTART',canvas.width/2,canvas.height/2+26)}}
  private choiceRects():Rect[]{const{canvas}=this.context,gap=8,width=Math.min(180,(canvas.width-32-gap*2)/3),height=Math.min(72,(canvas.height-150-gap*2)/3),gridHeight=height*3+gap*2,startX=(canvas.width-width*3-gap*2)/2,startY=(canvas.height-gridHeight)/2;return ABILITIES.map((_,i)=>({x:startX+i%3*(width+gap),y:startY+Math.floor(i/3)*(height+gap),width,height}))}
}
