import type {World} from '../ecs/world';
import type {InputState} from '../input';
import {ABILITIES, type GameState, RAINBOW_COLORS, STAGE_COUNT, VIEW_HEIGHT, VIEW_WIDTH, WORLD_HEIGHT, WORLD_WIDTH} from '../state';
import unicornUrl from '../assets/unicorn-atlas.webp';
import enemyUrl from '../assets/enemy-atlas.webp';
import gateUrl from '../assets/rainbow-gate.webp';

const FIRE=['#66eeff','#087f9d','#073344'];
const SKY=['#78b9e4','#91cce8','#addde9','#e7d7ac','#308dcc','#46a5d7','#69bde0','#9bd6e3','#45427c','#765080','#b75f78','#e68a68','#10162f','#171d3e','#25234c','#392950'],CLOUD=['#f7e6bd','#c1d8dc','#dff4ed','#9ccbd1','#f6b891','#b66d7e','#68739b','#343959'],GROUPS=[['MAP','#173d57','#247da0','#74dcff'],['ATTACK','#4b1c43','#a63d83','#ff87d8'],['ABILITY','#29452d','#578f42','#a9ee7d']];

const LETTERS="ABCDEGILMNOPRSTUWY0123456789:./+",PIXELS="ehhvhhhuhhuhhufgggggfuhhhhhuvgguggvfggnhhfv44444vggggggvhrllhhhhpljhhhehhhhheuhhuggguhhukihfgge11uv444444hhhhhhehhhllrhhha4444ehjlphe4c4444eeh1248vu11e11u26aiv22vggu11uegguhhev124888ehhehheehhf11e0440440000004411248gg044v440";

interface Rect {x:number;y:number;width:number;height:number}

export class RenderSystem {
  cameraX=WORLD_WIDTH/2; cameraY=WORLD_HEIGHT/2; viewWidth=VIEW_WIDTH; viewHeight=VIEW_HEIGHT; visiblePrisms=0;
  private stride=0;private lastPlayerX=NaN;private lastPlayerY=NaN;private screenWidth=VIEW_WIDTH;private screenHeight=VIEW_HEIGHT;private readonly unicorn=new Image();private readonly enemy=new Image();private readonly gate=new Image();
  constructor(private readonly context:CanvasRenderingContext2D,private readonly input:InputState){this.unicorn.src=unicornUrl;this.enemy.src=enemyUrl;this.gate.src=gateUrl;this.context.imageSmoothingEnabled=false}

  draw(world:World,state:GameState,time:number):void{
    const c=this.context,{canvas}=c,dpr=canvas.width/(canvas.clientWidth||innerWidth);this.screenWidth=canvas.clientWidth||innerWidth;this.screenHeight=canvas.clientHeight||innerHeight;c.setTransform(dpr,0,0,dpr,0,0);c.imageSmoothingEnabled=false;
    if(state.phase==='complete'){this.drawEnding(state);return}
    if(state.phase==='title'){this.drawTitle(time);return}
    this.viewWidth=Math.min(this.screenWidth,WORLD_WIDTH);this.viewHeight=Math.min(this.screenHeight,WORLD_HEIGHT);
    const player=world.players.values().next().value,pp=player===undefined?undefined:world.positions.get(player);
    const clamp=(v:number,s:number,l:number)=>s>=l?l/2:Math.max(s/2,Math.min(l-s/2,v));
    this.cameraX=Math.round(clamp(pp?.x??WORLD_WIDTH/2,this.viewWidth,WORLD_WIDTH));this.cameraY=Math.round(clamp(pp?.y??WORLD_HEIGHT/2,this.viewHeight,WORLD_HEIGHT));this.visiblePrisms=0;
    c.fillStyle=SKY[(state.stage<2?0:state.stage<5?4:state.stage<8?8:12)]??'#090611';c.fillRect(0,0,this.screenWidth,this.screenHeight);c.save();
    c.translate(this.screenWidth/2,this.screenHeight/2);c.translate(-this.cameraX,-this.cameraY);this.drawArena(state.stage,time);
    for(const prism of world.prisms){if(world.consumed.has(prism))continue;const p=world.positions.get(prism),c=world.prismColors.get(prism);if(p&&c){if(Math.abs(p.x-this.cameraX)<this.viewWidth/2+24&&Math.abs(p.y-this.cameraY)<this.viewHeight/2+24)this.visiblePrisms++;this.drawPrism(p.x,p.y,time+prism*300,c.index)}}
    for(const gate of world.gates){const p=world.positions.get(gate);if(p)this.drawGate(p.x,p.y,time,state.collected>=state.total)}
    if(pp&&state.abilities&1<<8)this.drawAura(pp.x,pp.y,time);
    for(const [entity,wave]of world.waves){const p=world.positions.get(entity)!;if(wave.value>0){c.save();c.globalAlpha=wave.value/.6;c.strokeStyle=RAINBOW_COLORS[world.prismColors.get(entity)!.index]??'#fff';c.lineWidth=6;c.beginPath();c.arc(p.x,p.y,300-460*wave.value,0,7);c.stroke();c.restore()}}
    for(const [entity,shot]of world.projectiles){if(world.consumed.has(entity))continue;const p=world.positions.get(entity),v=world.velocities.get(entity);if(p)this.drawShot(p.x,p.y,v?.x??1,v?.y??0,shot.friendly,time+entity*90,!!pp&&!shot.friendly&&!!(state.abilities&1<<8)&&Math.hypot(p.x-pp.x,p.y-pp.y)<200)}
    for(const [entity,enemy]of world.enemies){if(world.consumed.has(entity))continue;const p=world.positions.get(entity),v=world.velocities.get(entity),d=p&&pp?Math.hypot(p.x-pp.x,p.y-pp.y):999;if(p)this.drawEnemy(p.x,p.y,enemy.type,enemy.health,!!pp&&!!(state.abilities&1<<8)&&d<200,pp?.x??p.x,state.phase==='play'&&Math.hypot(v?.x??0,v?.y??0)>1?time+entity*97:0,enemy.type===1&&d<260&&(world.cooldowns.get(entity)?.value??1)<.25)}
    if(pp&&player!==undefined){const f=world.facings.get(player)??{x:1,y:0},v=world.velocities.get(player),moving=state.phase==='play'&&Math.hypot(v?.x??0,v?.y??0)>1,d=Math.hypot(pp.x-this.lastPlayerX,pp.y-this.lastPlayerY);if(moving&&Number.isFinite(d)&&d<40)this.stride+=d*.08;else if(!moving)this.stride=0;this.lastPlayerX=pp.x;this.lastPlayerY=pp.y;if(state.meleeFlash>0)this.drawCharge(pp.x,pp.y,f.x,f.y,state.meleeFlash);this.drawUnicorn(pp.x,pp.y,f.x,f.y,state.invulnerable>0,1,moving)}
    c.restore();this.drawHud(world,state);if(state.phase==='play'){this.drawStick();this.drawAttack(state)}else if(state.phase==='start'){c.globalAlpha=1-state.stageElapsed/.3;c.fillStyle='#090611';c.fillRect(0,0,this.screenWidth,this.screenHeight);c.globalAlpha=1}else this.drawOverlay(state);if(state.phase!=='start')this.drawTime(state);
    if(DEBUG){c.textAlign='left';c.font='12px monospace';c.fillStyle='#7cf';c.fillText(`DEBUG: x=${pp?.x.toFixed(1)} y=${pp?.y.toFixed(1)} enemies=${world.enemies.size} shots=${world.projectiles.size}`,16,this.screenHeight-14)}
  }

  choiceAt(x:number,y:number):number{return this.choiceRects().findIndex(c=>x>=c.x&&x<=c.x+c.width&&y>=c.y&&y<=c.y+c.height)}
  attackAt(x:number,y:number,state:GameState):boolean{if(!(state.abilities&1<<3))return false;const b=this.attackRect();return Math.hypot(x-(b.x+b.width/2),y-(b.y+b.height/2))<b.width/2}

  private drawArena(stage:number,time:number):void{const c=this.context,k=stage<2?0:stage<5?1:stage<8?2:3,o=k*4,g=c.createLinearGradient(0,0,0,WORLD_HEIGHT);for(let i=0;i<4;i++)g.addColorStop(i/3,SKY[o+i]!);c.fillStyle=g;c.fillRect(0,0,WORLD_WIDTH,WORLD_HEIGHT);if(k===3){c.fillStyle='#cbd7ff';for(let i=0;i<30;i++)c.fillRect(i*443%WORLD_WIDTH,i*281%WORLD_HEIGHT,2,2)}c.globalAlpha=.45;for(let i=0;i<36;i++){const x=(i*509+time*(.004+i%3*.002))%(WORLD_WIDTH+240)-120,y=i*277%WORLD_HEIGHT,s=i%5?3:4;for(let j=0;j<2;j++){c.fillStyle=CLOUD[k*2+1-j]!;c.beginPath();c.ellipse(x,y+(1-j)*7,18*s,6*s,0,0,7);c.ellipse(x-7*s,y-3*s+(1-j)*7,8*s,7*s,0,0,7);c.ellipse(x+3*s,y-6*s+(1-j)*7,9*s,9*s,0,0,7);c.fill()}}c.globalAlpha=1;c.fillStyle=k===3?'#cbd7ff':'#fff6bd';c.beginPath();c.arc(this.cameraX+this.viewWidth/2-76,this.cameraY-this.viewHeight/2+60,k===3?22:30,0,7);c.fill()}
  private drawTitle(time:number):void{const c=this.context,w=this.screenWidth,h=this.screenHeight;for(let i=0;i<4;i++){c.fillStyle=SKY[i]??'#78b9e4';c.fillRect(0,i*h/4,w,h/4+1)}for(let i=0;i<5;i++){const x=(i*173+time*.01)%w,y=70+i*83%(h-160);c.fillStyle='#ffffff45';c.fillRect(x,y,70,12);c.fillRect(x+16,y-8,40,8)}const small=h<440,size=small?3:w<500?4:7;this.pixelText('UNICORN',w/2,small?18:45,size,'#fff8d4',true);this.pixelText('PRISM ESCAPE',w/2,(small?18:45)+size*9,small?2:w<500?3:5,'',true);this.pixelText('COLLECT 7 COLORS',w/2,h*(small?.3:.36),2,'#30435f');this.pixelText('ESCAPE 10 STAGES',w/2,h*(small?.3:.36)+25,2,'#30435f');this.drawGate(w/2-(small?60:0),h*.58,time);this.drawUnicorn(w/2+(small?60:0),h*.58+(small?0:68),0,-1,false);this.pixelText('PRESS SPACE OR TAP',w/2,h-83,2,'#fffdf4',true);this.pixelText('ARROWS / WASD + SPACE',w/2,h-47,2,'#394660')}
  private pixelText(text:string,x:number,y:number,size:number,color='#fff',shadow=false):void{const c=this.context;if(shadow)this.pixelText(text,x+2,y+3,size,'#263355');x=Math.round(x-(text.length*6-1)*size/2);y=Math.round(y);for(let i=0;i<text.length;i++){const letter=LETTERS.indexOf(text[i]??' ');if(letter<0)continue;c.fillStyle=color||RAINBOW_COLORS[i%7]||'#fff';for(let j=0;j<35;j++)if(parseInt(PIXELS[letter*7+Math.floor(j/5)]??'0',32)&1<<(4-j%5))c.fillRect(x+(i*6+j%5)*size,y+Math.floor(j/5)*size,size,size)}}
  private formatTime(seconds:number):string{const ms=Math.round(seconds*1000);return Math.floor(ms/60000)+new Date(ms).toISOString().slice(16,23)}
  private drawEnding(state:GameState):void{const c=this.context,w=this.screenWidth,h=this.screenHeight,narrow=w<500&&h>=480,compact=h<480,y=compact?65:narrow?117:137;this.drawArena(9,0);this.pixelText('YOU ESCAPED',w/2,compact?12:36,compact?2:narrow?3:5,'',true);this.pixelText('10 RAINBOWS RESTORED',w/2,compact?37:narrow?72:86,compact?1:2,'#b5bfd8');c.fillStyle='#202c47';c.fillRect(w/2-138,y-9,276,77);this.pixelText('TOTAL',w/2,y+1,2,'#acbddc');this.pixelText(this.formatTime(state.elapsed),w/2,y+31,3,'#ffe08a');const gap=Math.min(27,(h-y-170)/10),scale=compact?1:2;for(let i=0;i<10;i++){const yy=y+91+i*gap;this.pixelText('STAGE '+(i+1),w/2-(compact?47:93),yy,scale,'#abb8d0');this.pixelText(this.formatTime(state.stageTimes[i]??0),w/2+(compact?25:43),yy,scale,'#f5f4e9')}this.pixelText('WELL DONE',w/2,h-71,1,'#b5bfd8');this.pixelText('TAP OR R TO RESTART',w/2,h-43,2,'#ffe08a')}

  private drawPrism(x:number,y:number,time:number,color:number):void{this.context.save();this.context.translate(x,y);this.context.rotate(time/900);this.context.fillStyle=RAINBOW_COLORS[color]??'#fff';this.context.beginPath();this.context.moveTo(0,-14);this.context.lineTo(9,0);this.context.lineTo(0,14);this.context.lineTo(-9,0);this.context.closePath();this.context.fill();this.context.fillStyle='#fff7';this.context.beginPath();this.context.moveTo(0,-14);this.context.lineTo(0,0);this.context.lineTo(-9,0);this.context.fill();this.context.restore()}
  private drawGate(x:number,y:number,time:number,open=true):void{const c=this.context,p=Math.floor(time/130);c.save();c.translate(Math.round(x),Math.round(y+Math.sin(time/180)*2));c.imageSmoothingEnabled=false;if(!open)c.filter='grayscale(1)';if(this.gate.complete)c.drawImage(this.gate,-40,-44,80,88);for(let i=0;open&&i<3;i++){c.globalAlpha=.45+(p+i)%3*.2;c.fillStyle=RAINBOW_COLORS[(p+i*2)%7]??'#fff';const sx=(i*11+p*3)%24-12,sy=(i*17+p*2)%38-15;c.fillRect(sx,sy,2,2)}c.restore()}
  private drawEnemy(x:number,y:number,type:number,health:number,slowed:boolean,targetX:number,time:number,charging:boolean):void{const c=this.context,size=type===2?96:48,half=size/2,top=size*.75,k=time?Math.round(Math.sin(time/140)*(type===2?6:2)):0;c.save();c.translate(Math.round(x),Math.round(y));c.imageSmoothingEnabled=false;c.fillStyle='#05030a88';c.fillRect(-half+6,half-3,size-12,3);c.scale(targetX<x?-1:1,1);if(this.enemy.complete){c.drawImage(this.enemy,type*48,0,size,top,-half,-half,size,top);for(let i=0;i<2;i++)c.drawImage(this.enemy,type*48+i*half,top,half,size-top,-half+i*half,top-half-Math.max(0,i?k:-k),half,size-top)}if(charging){c.fillStyle='#fff';c.fillRect(17,-4,3,3)}if(type===2){c.fillStyle='#ff9d00';for(let i=0;i<Math.ceil(health);i++)c.fillRect(-29+i*10,-55,7,4)}if(slowed){c.strokeStyle='#75fff022';c.lineWidth=4;c.beginPath();c.arc(0,0,type===2?56:26,0,7);c.stroke()}c.restore()}
  private drawShot(x:number,y:number,vx:number,vy:number,friendly:boolean,time:number,slowed:boolean):void{const c=this.context,j=Math.floor(time/70)%3-1;c.save();c.translate(Math.round(x),Math.round(y));c.rotate(Math.atan2(vy,vx));if(friendly){const line=()=>{c.beginPath();c.moveTo(-20,1);c.lineTo(-13,-4);c.lineTo(-7,2);c.lineTo(0,-3);c.lineTo(7,1);c.lineTo(14,-5);c.lineTo(20,-2)};c.strokeStyle='#6949c5';c.lineWidth=5;line();c.stroke();c.strokeStyle='#fff3a0';c.lineWidth=2;line();c.stroke();c.lineWidth=3;c.strokeStyle='#ff526b';c.beginPath();c.moveTo(-7,2);c.lineTo(-11,8+j);c.stroke();c.strokeStyle='#45d66b';c.beginPath();c.moveTo(0,-3);c.lineTo(-2,-9-j);c.stroke();c.strokeStyle='#42a5ff';c.beginPath();c.moveTo(7,1);c.lineTo(12,7+j);c.stroke();c.strokeStyle='#fff';c.lineWidth=1;c.stroke()}else{for(let i=3;i>0;i--){c.save();c.translate((3-i)*2.16,0);c.scale(i*.216,i*.216);c.fillStyle=FIRE[i-1]!;c.beginPath();c.moveTo(13,0);c.quadraticCurveTo(10,-13,-2,-9);c.quadraticCurveTo(-12,-7,-24,-17+j*3);c.quadraticCurveTo(-22,-5,-12,-3);c.quadraticCurveTo(-22,1,-32,j*4);c.quadraticCurveTo(-22,9,-10,5);c.quadraticCurveTo(-13,12,-23,16-j*3);c.quadraticCurveTo(-7,15,1,10);c.quadraticCurveTo(12,9,13,0);c.fill();c.restore()}}if(slowed){c.strokeStyle='#75fff022';c.lineWidth=2;c.strokeRect(friendly?-22:-23,-11,friendly?44:39,22)}c.restore()}
  private drawCharge(x:number,y:number,fx:number,fy:number,life:number):void{for(let i=3;i>0;i--)this.drawUnicorn(x+fx*i*28,y+fy*i*28,fx,fy,false,life/.18*(.14+i*.08),false)}
  private drawAura(x:number,y:number,time:number):void{this.context.fillStyle='#64ffe808';this.context.strokeStyle='#75fff022';this.context.lineWidth=5;this.context.beginPath();this.context.arc(x,y,200+Math.sin(time/180)*5,0,7);this.context.fill();this.context.stroke()}
  private drawUnicorn(x:number,y:number,fx:number,fy:number,blink:boolean,alpha=1,moving=false):void{
    const sector=(Math.round(Math.atan2(fy,fx)/(Math.PI/4))+8)%8,map=[1,3,2,3,1,4,0,4],cell=map[sector]??1,flip=sector===3||sector===4||sector===7?-1:1,step=moving?Math.round(Math.sin(this.stride)*2):0,c=this.context;
    c.save();c.translate(Math.round(x),Math.round(y));c.scale(flip,1);c.globalAlpha=alpha*(blink&&Math.floor(performance.now()/80)%2?.35:1);
    if(this.unicorn.complete){const sx=cell*56,cut=cell>2?45:43,left=cell===1?10:0,split=[28,26,28,21,25][cell]!;
      if(!moving)c.drawImage(this.unicorn,sx,0,56,56,-28,-28,56,56);
      else{if(left)c.drawImage(this.unicorn,sx,cut,left,56-cut,-28,cut-28,left,56-cut);
        for(let i=0;i<2;i++){const start=i?split:left,width=(i?56:split)-start,k=i?-step:step;c.drawImage(this.unicorn,sx+start,cut,width,56-cut,start-28+(cell>2?0:k),cut-28-Math.max(0,k),width,56-cut)}
        c.drawImage(this.unicorn,sx,0,56,cut,-28,-28,56,cut);
      }
    }c.restore();
  }

  private drawHud(world:World,state:GameState):void{const c=this.context,w=this.screenWidth,h=this.screenHeight;c.textAlign='left';c.font='bold 18px monospace';c.fillStyle='#fff';c.fillText(state.collected>=state.total?(w<600?'GATE OPEN':'FIND THE RAINBOW GATE'):`RAINBOW ${state.collected}/${state.total}`,16,28);c.textAlign='right';c.fillText(`STAGE ${state.stage+1}/${STAGE_COUNT}`,w-16,28);for(let color=0;color<7;color++){const x=25+color*28;c.save();c.translate(x,w<600?79:51);c.rotate(Math.PI/4);c.fillStyle=state.rainbowMask&1<<color?(RAINBOW_COLORS[color]??'#fff'):'#21182e';c.fillRect(-6,-6,12,12);c.strokeStyle=RAINBOW_COLORS[color]??'#fff';c.strokeRect(-6,-6,12,12);c.restore()}if(state.abilities&7)this.drawMap(world,state)}
  private drawTime(state:GameState):void{this.context.textAlign='center';this.context.font='bold 18px monospace';this.context.fillStyle='#fff';this.context.fillText(this.formatTime(state.elapsed),this.screenWidth/2,this.screenWidth<600?56:28)}
  private drawMap(world:World,state:GameState):void{const w=Math.min(140,this.screenWidth*.32),h=w*.7,x=this.screenWidth-w-12,y=this.screenWidth<600?68:40;this.context.fillStyle='#1a1030dd';this.context.fillRect(x,y,w,h);this.context.strokeStyle='#fff5';this.context.strokeRect(x,y,w,h);const dot=(px:number,py:number,color:string,size=3)=>{this.context.fillStyle=color;this.context.fillRect(x+px/WORLD_WIDTH*w-size/2,y+py/WORLD_HEIGHT*h-size/2,size,size)};for(const gate of world.gates){const p=world.positions.get(gate);if(p)dot(p.x,p.y,state.collected>=state.total?(RAINBOW_COLORS[Math.floor(state.elapsed*8)%7]??'#fff'):'#999',7)}if(state.abilities&2)for(const prism of world.prisms){const p=world.positions.get(prism),c=world.prismColors.get(prism);if(p&&c)dot(p.x,p.y,RAINBOW_COLORS[c.index]??'#fff',4)}if(state.abilities&4)for(const entity of world.enemies.keys()){const p=world.positions.get(entity);if(p)dot(p.x,p.y,'#ff4b6e',4)}const player=world.players.values().next().value,p=player===undefined?undefined:world.positions.get(player);if(p)dot(p.x,p.y,'#fff',6)}
  private drawStick():void{const x=66,y=this.screenHeight-66;this.context.fillStyle='#ffffff22';this.context.beginPath();this.context.arc(x,y,44,0,7);this.context.fill();this.context.fillStyle='#ffffff88';this.context.beginPath();this.context.arc(x+this.input.moveX*28,y+this.input.moveY*28,18,0,7);this.context.fill()}
  private attackRect():Rect{const size=Math.min(82,this.screenWidth*.2);return{x:this.screenWidth-size-22,y:this.screenHeight-size-28,width:size,height:size}}
  private drawAttack(state:GameState):void{if(!(state.abilities&1<<3))return;const b=this.attackRect();this.context.fillStyle='#ff66cc55';this.context.beginPath();this.context.arc(b.x+b.width/2,b.y+b.height/2,b.width/2,0,7);this.context.fill();this.context.textAlign='center';this.context.fillStyle='#fff';this.context.font='bold 13px monospace';this.context.fillText('HORN',b.x+b.width/2,b.y+b.height/2+5)}
  private drawOverlay(state:GameState):void{const c=this.context,w=this.screenWidth,h=this.screenHeight;c.fillStyle='#090611e8';c.fillRect(0,0,w,h);c.textAlign='center';c.fillStyle='#fff';c.font='bold 28px monospace';if(state.phase==='upgrade'){const cards=this.choiceRects(),top=Math.min(...cards.map(c=>c.y)),bottom=Math.max(...cards.map(c=>c.y+c.height));c.font=`bold ${w<500?18:28}px monospace`;c.fillText(`STAGE ${state.stage+1} CLEAR - PICK 1 UPGRADE`,w/2,Math.max(28,top-38));for(let row=0;row<3;row++){const card=cards[row*3],group=GROUPS[row];if(card&&group){c.textAlign='left';c.font='bold 12px monospace';c.fillStyle=group[3]??'#fff';c.fillText(group[0]??'',card.x,card.y-6)}}c.textAlign='center';cards.forEach((card,index)=>{const active=!!(state.abilities&1<<index),available=!active&&(index%3===0||!!(state.abilities&1<<index-1)),selected=index===state.selectedAbility,group=GROUPS[Math.floor(index/3)];c.fillStyle=selected?(group?.[2]??'#7f4cff'):available||active?(group?.[1]??'#23143c'):'#160f22';c.fillRect(card.x,card.y,card.width,card.height);c.strokeStyle=selected&&available?(group?.[3]??'#fff'):active?(group?.[3]??'#6f5a91'):'#6f5a91';c.lineWidth=2;c.strokeRect(card.x,card.y,card.width,card.height);c.fillStyle=available||active?'#fff':'#756a88';c.font=`bold ${card.width<120?10:13}px monospace`;c.fillText(ABILITIES[index]?.[0]??'',card.x+card.width/2,card.y+card.height/2+4)});c.font=`${w<500?10:13}px monospace`;c.fillStyle='#e3d8f5';const ability=ABILITIES[state.selectedAbility];c.fillText(ability?.[1]??'',w/2,Math.min(h-34,bottom+22));c.fillStyle='#a996ca';c.fillText('ARROWS + SPACE  |  TAP TWICE',w/2,Math.min(h-14,bottom+42))}else if(state.phase==='failed'){c.fillText('THE RAINBOW BROKE',w/2,h/2-12);c.font='16px monospace';c.fillText('TAP OR R TO RETRY',w/2,h/2+26)}}
  private choiceRects():Rect[]{const gap=8,label=18,width=Math.min(180,(this.screenWidth-32-gap*2)/3),height=Math.max(28,Math.min(62,(this.screenHeight-150-label*3-gap*2)/3)),gridHeight=(height+label)*3+gap*2,startX=(this.screenWidth-width*3-gap*2)/2,startY=(this.screenHeight-gridHeight)/2;return ABILITIES.map((_,i)=>({x:startX+i%3*(width+gap),y:startY+Math.floor(i/3)*(height+label+gap)+label,width,height}))}
}
