import type {World} from '../ecs/world';
import type {InputState} from '../input';
import {ABILITIES, type GameState, RAINBOW_COLORS, STAGE_COUNT, VIEW_HEIGHT, VIEW_WIDTH, WORLD_HEIGHT, WORLD_WIDTH} from '../state';
import unicornUrl from '../assets/unicorn-atlas.webp';
import enemyUrl from '../assets/enemy-atlas.webp';
import gateUrl from '../assets/rainbow-gate.webp';

const SKY=['#78b9e4','#91cce8','#addde9','#e7d7ac','#308dcc','#46a5d7','#69bde0','#9bd6e3','#45427c','#765080','#b75f78','#e68a68','#10162f','#171d3e','#25234c','#392950'],CLOUD=['#f7e6bd','#c1d8dc','#dff4ed','#9ccbd1','#f6b891','#b66d7e','#68739b','#343959'],GROUPS=[['MAP','#173d57','#247da0','#74dcff'],['ATTACK','#4b1c43','#a63d83','#ff87d8'],['ABILITY','#29452d','#578f42','#a9ee7d']];

interface Rect {x:number;y:number;width:number;height:number}

export class RenderSystem {
  cameraX=WORLD_WIDTH/2; cameraY=WORLD_HEIGHT/2; viewWidth=VIEW_WIDTH; viewHeight=VIEW_HEIGHT; visiblePrisms=0;
  private stride=0;private lastPlayerX=NaN;private lastPlayerY=NaN;private width=VIEW_WIDTH;private height=VIEW_HEIGHT;private readonly unicorn=new Image();private readonly enemy=new Image();private readonly gate=new Image();
  constructor(private readonly context:CanvasRenderingContext2D,private readonly input:InputState){this.unicorn.src=unicornUrl;this.enemy.src=enemyUrl;this.gate.src=gateUrl;this.context.imageSmoothingEnabled=false}

  draw(world:World,state:GameState,time:number):void{
    const {canvas}=this.context,dpr=canvas.width/(canvas.clientWidth||innerWidth);this.width=canvas.clientWidth||innerWidth;this.height=canvas.clientHeight||innerHeight;this.context.setTransform(dpr,0,0,dpr,0,0);this.context.imageSmoothingEnabled=false;
    if(state.phase==='title'){this.drawTitle(time);return}
    this.viewWidth=Math.min(this.width,WORLD_WIDTH);this.viewHeight=Math.min(this.height,WORLD_HEIGHT);
    const player=world.players.values().next().value,pp=player===undefined?undefined:world.positions.get(player);
    const clamp=(v:number,s:number,l:number)=>s>=l?l/2:Math.max(s/2,Math.min(l-s/2,v));
    this.cameraX=Math.round(clamp(pp?.x??WORLD_WIDTH/2,this.viewWidth,WORLD_WIDTH));this.cameraY=Math.round(clamp(pp?.y??WORLD_HEIGHT/2,this.viewHeight,WORLD_HEIGHT));this.visiblePrisms=0;
    this.context.fillStyle=SKY[(state.stage<2?0:state.stage<5?4:state.stage<8?8:12)]??'#090611';this.context.fillRect(0,0,this.width,this.height);this.context.save();
    this.context.translate(this.width/2,this.height/2);this.context.translate(-this.cameraX,-this.cameraY);this.drawArena(state.stage,time);
    for(const prism of world.prisms){if(world.consumed.has(prism))continue;const p=world.positions.get(prism),c=world.prismColors.get(prism);if(p&&c){if(Math.abs(p.x-this.cameraX)<this.viewWidth/2+24&&Math.abs(p.y-this.cameraY)<this.viewHeight/2+24)this.visiblePrisms++;this.drawPrism(p.x,p.y,time+prism*300,c.index)}}
    for(const gate of world.gates){const p=world.positions.get(gate);if(p)this.drawGate(p.x,p.y,time)}
    if(pp&&state.abilities&1<<8)this.drawAura(pp.x,pp.y,time);
    for(const [entity,shot]of world.projectiles){if(world.consumed.has(entity))continue;const p=world.positions.get(entity),v=world.velocities.get(entity);if(p)this.drawShot(p.x,p.y,v?.x??1,v?.y??0,shot.friendly,time+entity*90,!!pp&&!shot.friendly&&!!(state.abilities&1<<8)&&Math.hypot(p.x-pp.x,p.y-pp.y)<200)}
    for(const [entity,enemy]of world.enemies){if(world.consumed.has(entity))continue;const p=world.positions.get(entity),v=world.velocities.get(entity),d=p&&pp?Math.hypot(p.x-pp.x,p.y-pp.y):999;if(p)this.drawEnemy(p.x,p.y,enemy.type,enemy.health,!!pp&&!!(state.abilities&1<<8)&&d<200,pp?.x??p.x,state.phase==='play'&&Math.hypot(v?.x??0,v?.y??0)>1?time+entity*97:0,enemy.type===1&&d<260&&(world.cooldowns.get(entity)?.value??1)<.25)}
    if(pp&&player!==undefined){const f=world.facings.get(player)??{x:1,y:0},v=world.velocities.get(player),moving=state.phase==='play'&&Math.hypot(v?.x??0,v?.y??0)>1,d=Math.hypot(pp.x-this.lastPlayerX,pp.y-this.lastPlayerY);if(moving&&Number.isFinite(d)&&d<40)this.stride+=d*.08;else if(!moving)this.stride=0;this.lastPlayerX=pp.x;this.lastPlayerY=pp.y;if(state.meleeFlash>0)this.drawCharge(pp.x,pp.y,f.x,f.y,state.meleeFlash);this.drawUnicorn(pp.x,pp.y,f.x,f.y,state.invulnerable>0,1,moving)}
    this.context.restore();this.drawHud(world,state);if(state.phase==='play'){this.drawStick();this.drawAttack(state)}else if(state.phase==='start'){this.context.globalAlpha=1-state.stageElapsed/.3;this.context.fillStyle='#090611';this.context.fillRect(0,0,this.width,this.height);this.context.globalAlpha=1}else this.drawOverlay(state);if(state.phase!=='start')this.drawTime(state);
    if(DEBUG){this.context.textAlign='left';this.context.font='12px monospace';this.context.fillStyle='#7cf';this.context.fillText(`DEBUG: x=${pp?.x.toFixed(1)} y=${pp?.y.toFixed(1)} enemies=${world.enemies.size} shots=${world.projectiles.size}`,16,this.height-14)}
  }

  choiceAt(x:number,y:number):number{return this.choiceRects().findIndex(c=>x>=c.x&&x<=c.x+c.width&&y>=c.y&&y<=c.y+c.height)}
  attackAt(x:number,y:number,state:GameState):boolean{if(!(state.abilities&1<<3))return false;const b=this.attackRect();return Math.hypot(x-(b.x+b.width/2),y-(b.y+b.height/2))<b.width/2}

  private drawArena(stage:number,time:number):void{const c=this.context,k=stage<2?0:stage<5?1:stage<8?2:3,o=k*4;for(let i=0;i<4;i++){c.fillStyle=SKY[o+i]??'#1a1030';c.fillRect(0,i*WORLD_HEIGHT/4,WORLD_WIDTH,WORLD_HEIGHT/4+1)}if(k===3){c.fillStyle='#cbd7ff';for(let i=0;i<30;i++)c.fillRect(i*443%WORLD_WIDTH,i*281%WORLD_HEIGHT,2,2)}c.globalAlpha=.65;for(let i=0;i<36;i++){const x=(i*509+time*(.004+i%3*.002))%(WORLD_WIDTH+240)-120,y=i*277%WORLD_HEIGHT,s=i%5?2:3;c.fillStyle=CLOUD[k*2+1]??'#888';c.fillRect(x-4*s,y+8*s,20*s,4*s);c.fillRect(x,y+4*s,24*s,6*s);c.fillStyle=CLOUD[k*2]??'#ccc';c.fillRect(x+2*s,y+2*s,18*s,6*s);c.fillRect(x+6*s,y-2*s,8*s,8*s)}c.globalAlpha=1;const x=this.cameraX+this.viewWidth/2-76,y=this.cameraY-this.viewHeight/2+38;c.fillStyle=k===3?'#cbd7ff':'#fff6bd';c.fillRect(x,y,k===3?14:24,24);if(k===3){c.fillStyle=SKY[o]??'#10162f';c.fillRect(x-6,y-4,12,20)}}
  private drawTitle(time:number):void{const c=this.context,w=this.width,h=this.height;for(let i=0;i<4;i++){c.fillStyle=SKY[i]??'#78b9e4';c.fillRect(0,i*h/4,w,h/4+1)}c.globalAlpha=.7;for(let i=0;i<5;i++){const x=(i*211+time*.01)%(w+120)-60,y=50+i*173%(h-140),s=2+i%2;c.fillStyle=CLOUD[1]??'#c1d8dc';c.fillRect(x-4*s,y+8*s,20*s,4*s);c.fillRect(x,y+4*s,24*s,6*s);c.fillStyle=CLOUD[0]??'#f7e6bd';c.fillRect(x+2*s,y+2*s,18*s,6*s);c.fillRect(x+6*s,y-2*s,8*s,8*s)}c.globalAlpha=1;c.textAlign='center';c.lineWidth=3;c.strokeStyle='#31204c';c.font=`bold ${Math.min(56,w/11)}px monospace`;c.strokeText('UNICORN',w/2,h*.1);c.fillStyle='#fff';c.fillText('UNICORN',w/2,h*.1);const t='PRISM ESCAPE',z=Math.min(46,w/13),a=z*.61;c.font=`bold ${z}px monospace`;for(let i=0;i<t.length;i++){const x=w/2+(i-(t.length-1)/2)*a;c.strokeText(t[i]??'',x,h*.19);c.fillStyle=RAINBOW_COLORS[i%7]??'#fff';c.fillText(t[i]??'',x,h*.19)}const gy=Math.round(h*.48);this.drawGate(w/2,gy,time);this.drawUnicorn(w/2,gy+90,0,-1,false);c.globalAlpha=.7+Math.sin(time/350)*.25;c.font='bold 18px monospace';c.strokeText('PRESS SPACE OR TAP',w/2,h-92);c.fillStyle='#fff';c.fillText('PRESS SPACE OR TAP',w/2,h-92);c.globalAlpha=1;c.fillStyle='#493663';c.font='14px monospace';c.fillText('ARROWS / WASD  +  SPACE',w/2,h-52)}
  private drawPrism(x:number,y:number,time:number,color:number):void{this.context.save();this.context.translate(x,y);this.context.rotate(time/900);this.context.fillStyle=RAINBOW_COLORS[color]??'#fff';this.context.beginPath();this.context.moveTo(0,-14);this.context.lineTo(9,0);this.context.lineTo(0,14);this.context.lineTo(-9,0);this.context.closePath();this.context.fill();this.context.fillStyle='#fff7';this.context.beginPath();this.context.moveTo(0,-14);this.context.lineTo(0,0);this.context.lineTo(-9,0);this.context.fill();this.context.restore()}
  private drawGate(x:number,y:number,time:number):void{const c=this.context,p=Math.floor(time/130);c.save();c.translate(Math.round(x),Math.round(y+Math.sin(time/180)*2));c.imageSmoothingEnabled=false;if(this.gate.complete)c.drawImage(this.gate,-40,-44,80,88);for(let i=0;i<3;i++){c.globalAlpha=.45+(p+i)%3*.2;c.fillStyle=RAINBOW_COLORS[(p+i*2)%7]??'#fff';const sx=(i*11+p*3)%24-12,sy=(i*17+p*2)%38-15;c.fillRect(sx,sy,2,2)}c.restore()}
  private drawEnemy(x:number,y:number,type:number,health:number,slowed:boolean,targetX:number,time:number,charging:boolean):void{const c=this.context;c.save();c.translate(Math.round(x),Math.round(y));c.imageSmoothingEnabled=false;if(type===0){const s=time?Math.sin(time/150):0,b=Math.round(Math.abs(s)*2),w=Math.round(s*2),k=Math.round(s*2);c.fillStyle='#05030a88';c.fillRect(-16,21,32,3);c.translate(w,-b);c.scale(targetX<x?-1:1,1);c.rotate(s*.035);if(this.enemy.complete){c.drawImage(this.enemy,0,0,48,36,-24,-24,48,36);c.drawImage(this.enemy,0,34,24,14,-24+k,10-Math.max(0,k),24,14);c.drawImage(this.enemy,24,34,24,14,-k,10-Math.max(0,-k),24,14)}}else if(type===1){const s=time?Math.sin(time/250):0,w=time?Math.round(Math.sin(time/180)*2):0,k=time?Math.round(Math.sin(time/140)*2):0;c.fillStyle='#05030a77';c.fillRect(-15,21,30,3);c.translate(w,Math.round(s*2));c.scale(targetX<x?-1:1,1);c.rotate(w*.012);if(this.enemy.complete){c.drawImage(this.enemy,48,0,48,35,-24,-24,48,35);c.drawImage(this.enemy,48,30,48,18,-24+k,6,48,18)}c.fillStyle='#6ef';for(let i=0;i<2;i++)c.fillRect(Math.round(Math.cos(time/260+i*3.14)*20)-1,Math.round(Math.sin(time/260+i*3.14)*12)-1,3,3);if(charging){c.fillStyle='#fff';c.fillRect(-2,-2,4,4)}}else{const w=time?Math.round(Math.sin(time/180)*2):0;c.fillStyle='#05030a99';c.fillRect(-42+w,38,84,5);c.translate(w,11);c.scale(targetX<x?-1:1,1);if(this.enemy.complete){for(let i=0;i<4;i++){const step=time?Math.sin(time/140+(i&1)*Math.PI):0,lift=Math.max(0,Math.round(step*8));c.drawImage(this.enemy,96+i*24,62,24,34,-48+i*24+Math.round(step*3),14-lift,24,34)}c.drawImage(this.enemy,96,0,96,62,-48,-48,96,62)}c.fillStyle='#ff9d00';for(let i=0;i<Math.ceil(health);i++)c.fillRect(-29+i*10,-55,7,4)}if(slowed){c.strokeStyle='#75fff022';c.lineWidth=4;c.beginPath();c.arc(0,0,type===2?56:26,0,7);c.stroke()}c.restore()}
  private drawShot(x:number,y:number,vx:number,vy:number,friendly:boolean,time:number,slowed:boolean):void{const c=this.context,j=Math.floor(time/70)%3-1;c.save();c.translate(Math.round(x),Math.round(y));c.rotate(Math.atan2(vy,vx));c.lineJoin='miter';c.lineCap='butt';if(friendly){const line=()=>{c.beginPath();c.moveTo(-20,1);c.lineTo(-13,-4);c.lineTo(-7,2);c.lineTo(0,-3);c.lineTo(7,1);c.lineTo(14,-5);c.lineTo(20,-2)};c.strokeStyle='#6949c5';c.lineWidth=5;line();c.stroke();c.strokeStyle='#fff3a0';c.lineWidth=2;line();c.stroke();c.lineWidth=3;c.strokeStyle='#ff526b';c.beginPath();c.moveTo(-7,2);c.lineTo(-11,8+j);c.stroke();c.strokeStyle='#45d66b';c.beginPath();c.moveTo(0,-3);c.lineTo(-2,-9-j);c.stroke();c.strokeStyle='#42a5ff';c.beginPath();c.moveTo(7,1);c.lineTo(12,7+j);c.stroke();c.strokeStyle='#fff';c.lineWidth=1;c.stroke()}else{c.fillStyle='#3b1025';c.beginPath();c.moveTo(-3,-5);c.lineTo(-17,-10+j);c.lineTo(-12,-3);c.lineTo(-21,-5-j);c.lineTo(-13,0);c.lineTo(-20,7+j);c.lineTo(-9,3);c.lineTo(-15,11-j);c.lineTo(0,5);c.fill();c.beginPath();c.moveTo(0,-9);c.lineTo(8,-8);c.lineTo(14,-3);c.lineTo(14,3);c.lineTo(8,8);c.lineTo(0,8);c.lineTo(-5,4);c.lineTo(-5,-4);c.fill();c.fillStyle='#74172c';c.fillRect(-2,-6,9,12);c.fillStyle='#b52b27';c.fillRect(3,-3,8,7);c.fillStyle='#e05a2a';c.fillRect(6,-1,4,3)}if(slowed){c.strokeStyle='#75fff022';c.lineWidth=2;c.strokeRect(friendly?-22:-23,-11,friendly?44:39,22)}c.restore()}
  private drawCharge(x:number,y:number,fx:number,fy:number,life:number):void{for(let i=3;i>0;i--)this.drawUnicorn(x+fx*i*28,y+fy*i*28,fx,fy,false,life/.18*(.14+i*.08),false)}
  private drawAura(x:number,y:number,time:number):void{this.context.fillStyle='#64ffe808';this.context.strokeStyle='#75fff022';this.context.lineWidth=5;this.context.beginPath();this.context.arc(x,y,200+Math.sin(time/180)*5,0,7);this.context.fill();this.context.stroke()}
  private drawUnicorn(x:number,y:number,fx:number,fy:number,blink:boolean,alpha=1,moving=false):void{
    const sector=(Math.round(Math.atan2(fy,fx)/(Math.PI/4))+8)%8,map=[1,3,2,3,1,4,0,4],cell=map[sector]??1,flip=sector===3||sector===4||sector===7?-1:1,step=moving?Math.round(Math.sin(this.stride)*2):0,c=this.context;
    c.save();c.translate(Math.round(x),Math.round(y));c.scale(flip,1);c.globalAlpha=alpha*(blink&&Math.floor(performance.now()/80)%2?.35:1);
    if(this.unicorn.complete){const sx=cell*48,cut=37,left=cell===1?9:0,split=cell===1?22:24;
      if(!moving)c.drawImage(this.unicorn,sx,0,48,48,-24,-24,48,48);
      else{if(left)c.drawImage(this.unicorn,sx,cut,left,48-cut,-24,cut-24,left,48-cut);
        for(let i=0;i<2;i++){const start=i?split:left,width=(i?48:split)-start,k=i?-step:step;c.drawImage(this.unicorn,sx+start,cut,width,48-cut,start-24+k,cut-24-Math.max(0,k),width,48-cut)}
        c.drawImage(this.unicorn,sx,0,48,cut,-24,-24,48,cut);
      }
    }c.restore();
  }

  private drawHud(world:World,state:GameState):void{this.context.textAlign='left';this.context.font='bold 18px monospace';this.context.fillStyle='#fff';this.context.fillText(world.gates.size?(this.width<600?'GATE OPEN':'FIND THE RAINBOW GATE'):`RAINBOW ${state.collected}/${state.total}`,16,28);this.context.textAlign='right';this.context.fillText(`STAGE ${state.stage+1}/${STAGE_COUNT}`,this.width-16,28);for(let color=0;color<7;color++){const x=25+color*24;this.context.save();this.context.translate(x,this.width<600?79:51);this.context.rotate(Math.PI/4);this.context.fillStyle=state.rainbowMask&1<<color?(RAINBOW_COLORS[color]??'#fff'):'#21182e';this.context.fillRect(-6,-6,12,12);this.context.strokeStyle=RAINBOW_COLORS[color]??'#fff';this.context.strokeRect(-6,-6,12,12);this.context.restore()}if(state.abilities&7)this.drawMap(world,state)}
  private drawTime(state:GameState):void{this.context.textAlign='center';this.context.font='bold 18px monospace';this.context.fillStyle='#fff';this.context.fillText(new Date(state.elapsed*1e3).toISOString().slice(14,23),this.width/2,this.width<600?56:28)}
  private drawMap(world:World,state:GameState):void{const w=Math.min(140,this.width*.32),h=w*.7,x=this.width-w-12,y=this.width<600?68:40;this.context.fillStyle='#1a1030dd';this.context.fillRect(x,y,w,h);this.context.strokeStyle='#fff5';this.context.strokeRect(x,y,w,h);const dot=(px:number,py:number,color:string,size=3)=>{this.context.fillStyle=color;this.context.fillRect(x+px/WORLD_WIDTH*w-size/2,y+py/WORLD_HEIGHT*h-size/2,size,size)};for(const gate of world.gates){const p=world.positions.get(gate);if(p)dot(p.x,p.y,RAINBOW_COLORS[Math.floor(state.elapsed*8)%7]??'#fff',7)}if(state.abilities&2)for(const prism of world.prisms){const p=world.positions.get(prism),c=world.prismColors.get(prism);if(p&&c)dot(p.x,p.y,RAINBOW_COLORS[c.index]??'#fff',4)}if(state.abilities&4)for(const entity of world.enemies.keys()){const p=world.positions.get(entity);if(p)dot(p.x,p.y,'#ff4b6e',4)}const player=world.players.values().next().value,p=player===undefined?undefined:world.positions.get(player);if(p)dot(p.x,p.y,'#fff',6)}
  private drawStick():void{if(this.input.touchId<0)return;const{x:cx,y:cy}=this.context.canvas.getBoundingClientRect(),x=this.input.stickX-cx,y=this.input.stickY-cy;this.context.fillStyle='#ffffff22';this.context.beginPath();this.context.arc(x,y,44,0,7);this.context.fill();this.context.fillStyle='#ffffff88';this.context.beginPath();this.context.arc(x+this.input.moveX*28,y+this.input.moveY*28,18,0,7);this.context.fill()}
  private attackRect():Rect{const size=Math.min(82,this.width*.2);return{x:this.width-size-22,y:this.height-size-24,width:size,height:size}}
  private drawAttack(state:GameState):void{if(!(state.abilities&1<<3))return;const b=this.attackRect();this.context.fillStyle='#ff66cc55';this.context.beginPath();this.context.arc(b.x+b.width/2,b.y+b.height/2,b.width/2,0,7);this.context.fill();this.context.textAlign='center';this.context.fillStyle='#fff';this.context.font='bold 13px monospace';this.context.fillText('HORN',b.x+b.width/2,b.y+b.height/2+5)}
  private drawOverlay(state:GameState):void{this.context.fillStyle='#090611e8';this.context.fillRect(0,0,this.width,this.height);this.context.textAlign='center';this.context.fillStyle='#fff';this.context.font='bold 24px monospace';if(state.phase==='upgrade'){const cards=this.choiceRects(),top=Math.min(...cards.map(c=>c.y)),bottom=Math.max(...cards.map(c=>c.y+c.height));this.context.font=`bold ${this.width<500?18:24}px monospace`;this.context.fillText(`STAGE ${state.stage+1} CLEAR - PICK 1 UPGRADE`,this.width/2,Math.max(24,top-38));for(let row=0;row<3;row++){const card=cards[row*3],group=GROUPS[row];if(card&&group){this.context.textAlign='left';this.context.font='bold 12px monospace';this.context.fillStyle=group[3]??'#fff';this.context.fillText(group[0]??'',card.x,card.y-6)}}this.context.textAlign='center';cards.forEach((card,index)=>{const active=!!(state.abilities&1<<index),available=!active&&(index%3===0||!!(state.abilities&1<<index-1)),selected=index===state.selectedAbility,group=GROUPS[Math.floor(index/3)];this.context.fillStyle=selected?(group?.[2]??'#7f4cff'):available||active?(group?.[1]??'#23143c'):'#160f22';this.context.fillRect(card.x,card.y,card.width,card.height);this.context.strokeStyle=selected&&available?(group?.[3]??'#fff'):active?(group?.[3]??'#6f5a91'):'#6f5a91';this.context.lineWidth=2;this.context.strokeRect(card.x,card.y,card.width,card.height);this.context.fillStyle=available||active?'#fff':'#756a88';this.context.font=`bold ${card.width<120?10:13}px monospace`;this.context.fillText(ABILITIES[index]?.[0]??'',card.x+card.width/2,card.y+card.height/2+4)});this.context.font=`${this.width<500?10:13}px monospace`;this.context.fillStyle='#e3d8f5';const ability=ABILITIES[state.selectedAbility];this.context.fillText(ability?.[1]??'',this.width/2,Math.min(this.height-34,bottom+22));this.context.fillStyle='#a996ca';this.context.fillText('ARROWS + SPACE  |  TAP TWICE',this.width/2,Math.min(this.height-14,bottom+42))}else if(state.phase==='failed'){this.context.fillText('THE RAINBOW BROKE',this.width/2,this.height/2-12);this.context.font='16px monospace';this.context.fillText('PRESS R TO RETRY THIS STAGE',this.width/2,this.height/2+26)}else{this.context.fillText('ALL 10 RAINBOWS COMPLETE',this.width/2,this.height/2-12);this.context.font='16px monospace';this.context.fillText('PRESS R TO RESTART',this.width/2,this.height/2+26)}}
  private choiceRects():Rect[]{const gap=8,label=18,width=Math.min(180,(this.width-32-gap*2)/3),height=Math.max(28,Math.min(62,(this.height-150-label*3-gap*2)/3)),gridHeight=(height+label)*3+gap*2,startX=(this.width-width*3-gap*2)/2,startY=(this.height-gridHeight)/2;return ABILITIES.map((_,i)=>({x:startX+i%3*(width+gap),y:startY+Math.floor(i/3)*(height+label+gap)+label,width,height}))}
}
